package com.lavalloisir.beans.dao;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Connection;

import com.lavalloisir.beans.business.Leisure;
import com.lavalloisir.beans.business.Rating;
import com.lavalloisir.beans.business.User;


public class RatingDAOImpl implements RatingDAO{

	private DAOFactory daoFactory;
	
	RatingDAOImpl (DAOFactory daoFactory) {
		this.daoFactory = daoFactory;
	}
	
    private static final String SQL_INSERT = "INSERT INTO evaluation "
    		+ "(Note, Id_Utilisateur, Id_Loisir) "
    		+ "VALUES (?, ?, ?, NOW())";
    @Override
    public void create (Rating rating) throws IllegalArgumentException, DAOException {
    	Connection cnct = null;
    	PreparedStatement preparedStmt = null;
    	ResultSet autoGeneratedValues = null;
    	
    	try {
    		// Récupération d'une connexion depuis la Factory
    		cnct = daoFactory.getConnection();
    		preparedStmt = DAOUtil.initPreparedStatement(cnct, SQL_INSERT, true,
    		rating.getRating(), rating.getUser().getId(), rating.getLeisure().getId());
    		
    		int status = preparedStmt.executeUpdate();
    		
    		// Analyse du statut retourné par la requête d'insertion
    		if (status == 0) {
    			throw new DAOException("Echec de la création de l'évaluation, aucune ligne ajoutée à la table.");
    		}
    	} catch (SQLException e) {
    		throw new DAOException(e);
    	} finally {
    		DAOUtil.silentsClosing(autoGeneratedValues, preparedStmt, cnct);
    	}
    }
    
	private static final String SQL_SELECT = "SELECT "
			+ "Id, Note, Option_Courte, Commentaire, Date, Id_Utilisateur, Id_Loisir, "
			+ "FROM evaluation";
	
    
 // Implémentation de la méthode Lister() définie dans l'interface RatingDao
    @Override
    public Rating find(long idUser, long idLeisure) throws DAOException {
        Connection cnct = null;
        PreparedStatement preparedStmt = null;
        ResultSet rs = null;
        Rating rating = null;
        
        try {
        	// Récupération d'une connexion depuis la Factory
        	cnct = daoFactory.getConnection();
        	preparedStmt = DAOUtil.initPreparedStatement(cnct, SQL_SELECT, false);
        	rs = preparedStmt.executeQuery();
        	
        	// Parcours de la ligne de donnée de l'éventuel ResultSet retourné
        	while (rs.next()) {
        		rating = map(rs, idUser, idLeisure);
        	}
        } catch (SQLException e) {
        	throw new DAOException(e);
        } finally {
        	DAOUtil.silentsClosing(rs, preparedStmt, cnct);
        }
        
        return rating;
    }
    
    
	private static Rating map (ResultSet rs, long idUser, long idLeisure) throws SQLException {
		Rating rating = new Rating();
		rating.setRating(rs.getInt("Note"));
		
		LeisureDAOImpl leisureDAO = new LeisureDAOImpl();
		Leisure leisure = leisureDAO.find(idLeisure);
		rating.setLeisure(leisure);
		
		UserDAOImpl userDAO = new UserDAOImpl();
		User user = userDAO.find(idUser);
		rating.setUser(user);

		return rating;
	}
}